In [1]:
# Reinitialization of variables
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

with tf.Graph().as_default():
    with tf.Session() as sess:
        my_var = tf.Variable(tf.truncated_normal([3, 4]), name="myvar", dtype=tf.float32)
        my_var_plus = my_var.assign_add(np.ones([3, 4], dtype=np.float32) * 10.0)
        writer = tf.summary.FileWriter("./tf_summary", sess.graph)
        init = tf.variables_initializer([my_var])
        sess.run(init)
        for _ in range(10):
            res = sess.run(my_var_plus)
        print(res)
        ############################
        # reset variables
        init = tf.variables_initializer([my_var])
        print(my_var_plus)
        print(my_var)
        sess.run(init)
        res = sess.run(my_var_plus)
        print(res)
        writer.close()

[[  99.44104004   99.79423523   99.73307037   99.70156097]
 [  98.41956329   99.92144775  100.69115448  100.06777954]
 [  98.24476624  100.55198669  101.63265991  100.55345917]]
Tensor("AssignAdd:0", shape=(3, 4), dtype=float32_ref)
<tf.Variable 'myvar:0' shape=(3, 4) dtype=float32_ref>
[[ 11.01141834  10.50028419   8.16092014   8.9368372 ]
 [  9.79824543  10.25314903   9.32585144   9.27167606]
 [  9.53755474  11.76921844   8.60527992   8.91401196]]


In [3]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

with tf.Graph().as_default():
    with tf.Session() as sess:
        my_var = tf.Variable(tf.truncated_normal([3, 4]), name="myvar", dtype=tf.float32)
        my_var_plus = my_var.assign_add(np.ones([3, 4], dtype=np.float32) * 10.0)
        writer = tf.summary.FileWriter("./tf_summary", sess.graph)
        init = tf.variables_initializer([my_var])
        sess.run(init)
        for _ in range(10):
            res = sess.run(my_var_plus)
        print(res)
        ##################################
        # Assign new value
        my_var_reassign = my_var.assign(tf.ones([3, 4]))
        res = sess.run(my_var_reassign)
        print(res)
        writer.close()

[[ 100.72036743   99.80186462  100.80006409  101.42294312]
 [ 101.40226746   98.84672546  101.0247345    99.52185822]
 [ 100.11682129   98.39685059   99.96975708   99.50824738]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
